# Generated by Django 4.1 on 2022-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('date', models.DateField(blank=True, max_length=20)),
                ('desc', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
