# Generated by Django 4.1 on 2022-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblog',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
