# Generated by Django 4.1 on 2022-10-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_projectblog_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblog',
            name='desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
